/*
 * Copyright (c) 2024 Onomondo ApS. All rights reserved.
 * 
 * SPDX-License-Identifier: GPL-3.0-only 
 */

#pragma once

/* collection of status words described in TS 102 221 or 31.102 */
enum sim_status_word {
	SS_SW_NORMAL_ENDING = 0x9000,
	SS_SW_NORMAL_ENDING_EXTRA_INFO = 0x9100,
	SS_SW_NORMAL_ENDING_EXTRA_INFO_XFER = 0x9200,
	SS_SW_POSTP_SAT_BUSY_CANNOT_EXEC = 0x9300,

	SS_SW_WARN_NO_INFO_NV_UNCHANGED = 0x6200,
	SS_SW_WARNN_PART_OF_RET_MAY_CORRUPT = 0x6281,
	SS_SW_WARN_EOF_BEFORE_LE = 0x6282,
	SS_SW_WARN_SELECTED_FILE_INVALIDATED = 0x6283,
	SS_SW_WARN_SELECTED_FILE_IN_TERMINATED = 0x6285,
	SS_SW_WARN_MORE_DATA_AVAIL = 0x62f1,
	SS_SW_WARN_MORE_DATA_AVAIL_AND_PROACT_PEND = 0x62f3,
	SS_SW_WARN_MORE_DATA_EXPECTED = 0x63f1,
	SS_SW_WARN_VERIFICATION_FAILED_X_REMAIN = 0x63c0,

	SS_SW_ERR_EXEC_NO_INFO_NV_UNCHANGED = 0x6400,
	SS_SW_ERR_EXEC_MEMORY_PROBLEM = 0x6581,

	SS_SW_ERR_CHECKING_WRONG_LENGTH = 0x6700,
	SS_SW_ERR_CHECKING_WRONG_P1_P2 = 0x6b00,
	SS_SW_ERR_CHECKING_INS_INVALID = 0x6d00,
	SS_SW_ERR_CHECKING_CLA_INVALID = 0x6e00,
	SS_SW_ERR_CHECKING_NO_PRECISE_DIAG = 0x6f00,
	SS_SW_ERR_FUNCTION_IN_CLA_NOT_SUPP = 0x6800,
	SS_SW_ERR_FUNCTION_IN_CLA_NOT_SUPP_LCHAN = 0x6881,
	SS_SW_ERR_FUNCTION_IN_CLA_NOT_SUPP_SM = 0x6882,

	SS_SW_ERR_CMD_NOT_ALLOWED_NO_INFO = 0x6900,
	SS_SW_ERR_CMD_NOT_ALLOWED_INCOMP_FILE_STRUCT = 0x6981,
	SS_SW_ERR_CMD_NOT_ALLOWED_SECURITY_STATUS = 0x6982,
	SS_SW_ERR_CMD_NOT_ALLOWED_PIN_BLOCKED = 0x6983,
	SS_SW_ERR_CMD_NOT_ALLOWED_REF_DATA_INVALIDATED = 0x6984,
	SS_SW_ERR_CMD_NOT_ALLOWED_CONDITONS_NOT_SATISFIED = 0x6985,
	SS_SW_ERR_CMD_NOT_ALLOWED_NO_EF_SELECTED = 0x6986,
	SS_SW_ERR_CMD_NOT_ALLOWED_SEC_CHAN_NOT_SATISFIED = 0x6989,

	SS_SW_ERR_WRONG_PARAM_INCORRECT_DATA = 0x6a80,
	SS_SW_ERR_WRONG_PARAM_FUNCTION_NOT_SUPPORTED = 0x6a81,
	SS_SW_ERR_WRONG_PARAM_FILE_NOT_FOUND = 0x6a82,
	SS_SW_ERR_WRONG_PARAM_RECORD_NOT_FOUND = 0x6a83,
	SS_SW_ERR_WRONG_PARAM_ENOMEM = 0x6a84,
	SS_SW_ERR_WRONG_PARAM_INCORRECT_P1_TO_P2 = 0x6a86,
	SS_SW_ERR_WRONG_PARAM_LC_INCONSISTENT_WITH_P1_TO_P2 = 0x6a87,
	SS_SW_ERR_WRONG_PARAM_REFERENCED_DATA_NOT_FOUND = 0x6a88,

	SS_SW_APP_ERR_INCREASE_MAX_VALUE_REACHED = 0x9850,
	SS_SW_APP_ERR_AUTH_ERR_APP_SPECIFIC = 0x9862,
	SS_SW_APP_ERR_SECURITY_SESSION_OR_ASSOC_EXPIRED = 0x9863,
};

bool ss_sw_is_successful(uint16_t sw);
